# Experiment 2: Lower LR + Longer warmup
# Changes from baseline:
#   - lr_max: 0.001 -> 0.0003 (3x lower)
#   - lr_warmup_steps: 2000 -> 4000 (2x longer)
#
# Hypothesis: Transformers need gentler LR schedule, especially early in training

model:
  type: conformer
  n_input_features: 512
  d_model: 768
  n_heads: 8
  d_ff: 3072
  n_layers: 6
  conv_kernel_size: 31
  conformer_dropout: 0.1
  gradient_checkpointing: true
  patch_size: 14
  patch_stride: 4

  input_network:
    input_trainable: true
    input_layer_dropout: 0.2

gpu_number: '0'
mode: train
use_amp: true

use_wandb: true
wandb_project: brain-to-text
wandb_run_name: conformer-exp2-lr-warmup

output_dir: trained_models/conformer_exp2_lr_warmup
checkpoint_dir: trained_models/conformer_exp2_lr_warmup/checkpoint
init_from_checkpoint: false
init_checkpoint_path: null
save_best_checkpoint: true
save_all_val_steps: false
save_final_model: false
save_val_metrics: true
early_stopping: false
early_stopping_val_steps: 20

num_training_batches: 120000
lr_scheduler_type: cosine
lr_max: 0.0003  # CHANGED: 0.001 -> 0.0003
lr_min: 0.00001
lr_decay_steps: 120000
lr_warmup_steps: 4000  # CHANGED: 2000 -> 4000
lr_max_day: 0.005
lr_min_day: 0.0001
lr_decay_steps_day: 120000
lr_warmup_steps_day: 1000

beta0: 0.9
beta1: 0.98
epsilon: 0.000001
weight_decay: 0.01
weight_decay_day: 0
seed: 10
grad_norm_clip_value: 1.0

batches_per_train_log: 200
batches_per_val_step: 2000
batches_per_save: 0
log_individual_day_val_PER: true
log_val_skip_logs: false
save_val_logits: true
save_val_data: false

dataset:
  data_transforms:
    white_noise_std: 1.0
    constant_offset_std: 0.2
    random_walk_std: 0.0
    random_walk_axis: -1
    static_gain_std: 0.0
    random_cut: 3
    smooth_kernel_size: 100
    smooth_data: true
    smooth_kernel_std: 2

  neural_dim: 512
  batch_size: 32
  n_classes: 41
  max_seq_elements: 500
  days_per_batch: 4
  seed: 1
  num_dataloader_workers: 4
  loader_shuffle: false
  must_include_days: null
  test_percentage: 0.1
  feature_subset: null

  dataset_dir: ../data/hdf5_data_final
  bad_trials_dict: null
  sessions:
  - t15.2023.08.11
  - t15.2023.08.13
  - t15.2023.08.18
  - t15.2023.08.20
  - t15.2023.08.25
  - t15.2023.08.27
  - t15.2023.09.01
  - t15.2023.09.03
  - t15.2023.09.24
  - t15.2023.09.29
  - t15.2023.10.01
  - t15.2023.10.06
  - t15.2023.10.08
  - t15.2023.10.13
  - t15.2023.10.15
  - t15.2023.10.20
  - t15.2023.10.22
  - t15.2023.11.03
  - t15.2023.11.04
  - t15.2023.11.17
  - t15.2023.11.19
  - t15.2023.11.26
  - t15.2023.12.03
  - t15.2023.12.08
  - t15.2023.12.10
  - t15.2023.12.17
  - t15.2023.12.29
  - t15.2024.02.25
  - t15.2024.03.03
  - t15.2024.03.08
  - t15.2024.03.15
  - t15.2024.03.17
  - t15.2024.04.25
  - t15.2024.04.28
  - t15.2024.05.10
  - t15.2024.06.14
  - t15.2024.07.19
  - t15.2024.07.21
  - t15.2024.07.28
  - t15.2025.01.10
  - t15.2025.01.12
  - t15.2025.03.14
  - t15.2025.03.16
  - t15.2025.03.30
  - t15.2025.04.13
  dataset_probability_val:
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 0
  - 1
  - 1
  - 1
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
